name: Tests

on: [ push ]

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run unittests
        run: yarn jest

      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn run start

