name: Unit tests

on: [ push ]

jobs:
  unit-test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14.19.1

      - name: Install dependencies
        run: yarn

      - name: Run unit tests
        run: yarn jest